# Generated by Django 3.0 on 2020-10-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkatList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='名字')),
                ('page', models.IntegerField(default=0, verbose_name='ページ')),
                ('award', models.CharField(max_length=10, verbose_name='受賞')),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('adress', models.CharField(max_length=5, verbose_name='都道府県')),
                ('copy1', models.CharField(max_length=200, verbose_name='コピー（改行あり）')),
                ('copy2', models.CharField(max_length=200, verbose_name='コピー（改行なし）')),
            ],
        ),
    ]
