# Generated by Django 3.0 on 2020-10-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfomation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('infomation', models.CharField(max_length=3000, verbose_name='情報')),
            ],
        ),
        migrations.DeleteModel(
            name='SkatList',
        ),
    ]
