# Generated by Django 3.0 on 2020-10-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_auto_20201014_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='education',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='limit_balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='marriage',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='proba',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registered_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='result',
        ),
        migrations.AddField(
            model_name='customer',
            name='copy',
            field=models.CharField(default=1, max_length=3000, verbose_name='キャッチコピー'),
            preserve_default=False,
        ),
    ]
